@startuml
set separator none
title Government Department - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

Person_Ext(Citizen, "Citizen", $descr="A member of the public", $tags="", $link="")
System_Ext(GovNotify, "GovNotify", $descr="The Government Service for sending e-maills.", $tags="", $link="")
System(BankingSystem, "Banking System", $descr="Stores all of the core banking information about citizens, accounts, transactions, etc.", $tags="", $link="")

System_Boundary("GovernmentDepartment_boundary", "Government Department", $tags="") {
  Container(GovernmentDepartment.APIApplication, "API Application", $techn="Java and Spring MVC", $descr="Provides Internet banking functionality via a JSON/HTTPS API.", $tags="", $link="")
  ContainerDb(GovernmentDepartment.Database, "Database", $techn="Oracle Database Schema", $descr="Stores user registration information, hashed authentication credentials, access logs, etc.", $tags="", $link="")
  Container(GovernmentDepartment.SinglePageApplication, "Single-Page Application", $techn="JavaScript and Angular", $descr="Provides all of the Internet banking functionality to customers via their web browser.", $tags="", $link="")
  Container(GovernmentDepartment.MobileApp, "Mobile App", $techn="Xamarin", $descr="Provides a limited subset of the Internet banking functionality to customers via their mobile device.", $tags="", $link="")
  Container(GovernmentDepartment.WebApplication, "Web Application", $techn="Java and Spring MVC", $descr="Delivers the static content and the Internet banking single page application.", $tags="", $link="")
}

Rel_D(GovNotify, Citizen, "Sends e-mails to", $techn="", $tags="", $link="")
Rel_D(Citizen, GovernmentDepartment.WebApplication, "Visits someservice.gov.uk using", $techn="HTTPS", $tags="", $link="")
Rel_D(Citizen, GovernmentDepartment.SinglePageApplication, "Views account balances, and makes payments using", $techn="", $tags="", $link="")
Rel_D(Citizen, GovernmentDepartment.MobileApp, "Views account balances, and makes payments using", $techn="", $tags="", $link="")
Rel_D(GovernmentDepartment.WebApplication, GovernmentDepartment.SinglePageApplication, "Delivers to the citizen's web browser", $techn="", $tags="", $link="")
Rel_D(GovernmentDepartment.SinglePageApplication, GovernmentDepartment.APIApplication, "Makes API calls to", $techn="JSON/HTTPS", $tags="", $link="")
Rel_D(GovernmentDepartment.MobileApp, GovernmentDepartment.APIApplication, "Makes API calls to", $techn="JSON/HTTPS", $tags="", $link="")
Rel_D(GovernmentDepartment.APIApplication, GovernmentDepartment.Database, "Reads from and writes to", $techn="JDBC", $tags="", $link="")
Rel_D(GovernmentDepartment.APIApplication, BankingSystem, "Makes API calls to", $techn="XML/HTTPS", $tags="", $link="")
Rel_D(GovernmentDepartment.APIApplication, GovNotify, "Sends e-mail using", $techn="JSON/HTTPS", $tags="", $link="")

SHOW_LEGEND(true)
@enduml