@startuml
set separator none
title Government Department - Deployment - Live

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Deployment.puml

Deployment_Node(Live.Citizenscomputer, "Citizen's computer", "Microsoft Windows or Apple macOS", $tags="") {
  Deployment_Node(Live.Citizenscomputer.WebBrowser, "Web Browser", "Chrome, Firefox, Safari, or Edge", $tags="") {
    Container(Live.Citizenscomputer.WebBrowser.SinglePageApplication_1, "Single-Page Application", "JavaScript and Angular", "Provides all of the Internet banking functionality to customers via their web browser.", $tags="")
  }

}

Deployment_Node(Live.Bank, "Bank", "Bank data center", $tags="") {
  Deployment_Node(Live.Bank.bankapi, "bank-api*** (x8)", "Ubuntu 16.04 LTS", $tags="") {
    Deployment_Node(Live.Bank.bankapi.ApacheTomcat, "Apache Tomcat", "Apache Tomcat 8.x", $tags="") {
      Container(Live.Bank.bankapi.ApacheTomcat.APIApplication_1, "API Application", "Java and Spring MVC", "Provides Internet banking functionality via a JSON/HTTPS API.", $tags="")
    }

  }

  Deployment_Node(Live.Bank.bankdb01, "bank-db01", "Ubuntu 16.04 LTS", $tags="") {
    Deployment_Node(Live.Bank.bankdb01.OraclePrimary, "Oracle - Primary", "Oracle 12c", $tags="") {
      ContainerDb(Live.Bank.bankdb01.OraclePrimary.Database_1, "Database", "Oracle Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.", $tags="")
    }

  }

  Deployment_Node(Live.Bank.bankdb02, "bank-db02", "Ubuntu 16.04 LTS", $tags="") {
    Deployment_Node(Live.Bank.bankdb02.OracleSecondary, "Oracle - Secondary", "Oracle 12c", $tags="") {
      ContainerDb(Live.Bank.bankdb02.OracleSecondary.Database_1, "Database", "Oracle Database Schema", "Stores user registration information, hashed authentication credentials, access logs, etc.", $tags="")
    }

  }

  Deployment_Node(Live.Bank.bankprod001, "bank-prod001", $tags="") {
    System(Live.Bank.bankprod001.BankingSystem_1, "Banking System", "Stores all of the core banking information about citizens, accounts, transactions, etc.", $tags="")
  }

  Deployment_Node(Live.Bank.bankweb, "bank-web*** (x4)", "Ubuntu 16.04 LTS", $tags="") {
    Deployment_Node(Live.Bank.bankweb.ApacheTomcat, "Apache Tomcat", "Apache Tomcat 8.x", $tags="") {
      Container(Live.Bank.bankweb.ApacheTomcat.WebApplication_1, "Web Application", "Java and Spring MVC", "Delivers the static content and the Internet banking single page application.", $tags="")
    }

  }

}

Deployment_Node(Live.Citizensmobiledevice, "Citizen's mobile device", "Apple iOS or Android", $tags="") {
  Container(Live.Citizensmobiledevice.MobileApp_1, "Mobile App", "Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device.", $tags="")
}

Rel_D(Live.Bank.bankweb.ApacheTomcat.WebApplication_1, Live.Citizenscomputer.WebBrowser.SinglePageApplication_1, "Delivers to the citizen's web browser", $tags="")
Rel_D(Live.Citizensmobiledevice.MobileApp_1, Live.Bank.bankapi.ApacheTomcat.APIApplication_1, "Makes API calls to", "JSON/HTTPS", $tags="")
Rel_D(Live.Citizenscomputer.WebBrowser.SinglePageApplication_1, Live.Bank.bankapi.ApacheTomcat.APIApplication_1, "Makes API calls to", "JSON/HTTPS", $tags="")
Rel_D(Live.Bank.bankapi.ApacheTomcat.APIApplication_1, Live.Bank.bankdb01.OraclePrimary.Database_1, "Reads from and writes to", "JDBC", $tags="")
Rel_D(Live.Bank.bankapi.ApacheTomcat.APIApplication_1, Live.Bank.bankdb02.OracleSecondary.Database_1, "Reads from and writes to", "JDBC", $tags="")
Rel_D(Live.Bank.bankapi.ApacheTomcat.APIApplication_1, Live.Bank.bankprod001.BankingSystem_1, "Makes API calls to", "XML/HTTPS", $tags="")
Rel_D(Live.Bank.bankdb01.OraclePrimary, Live.Bank.bankdb02.OracleSecondary, "Replicates data to", $tags="")

SHOW_LEGEND(true)
@enduml