@startuml
set separator none
title Government Department - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

AddBoundaryTag("Government Body", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
Boundary(group_1, "Government Body", $tags="Government Body") {
  System(BankingSystem, "Banking System", $descr="Stores all of the core banking information about citizens, accounts, transactions, etc.", $tags="", $link="")
  WithoutPropertyHeader()
  AddProperty("Development Team","Dev/Internet Services")
  AddProperty("Owner","Customer Services")
  System(GovernmentDepartment, "Government Department", $descr="Allows citizens to view information about their accounts, and make payments.", $tags="", $link="")
}

Person(Citizen, "Citizen", $descr="A member of the public", $tags="", $link="")
System(GovNotify, "GovNotify", $descr="The Government Service for sending e-maills.", $tags="", $link="")

Rel(Citizen, GovernmentDepartment, "Views account balances, and makes payments using", $techn="", $tags="", $link="")
Rel(GovernmentDepartment, BankingSystem, "Gets account information from, and makes payments using", $techn="", $tags="", $link="")
Rel(GovernmentDepartment, GovNotify, "Sends e-mail using", $techn="", $tags="", $link="")
Rel(GovNotify, Citizen, "Sends e-mails to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml