@startuml
set separator none
title Government Department - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Enterprise_Boundary(enterprise, "Government Body") {
  System(BankingSystem, "Banking System", $descr="Stores all of the core banking information about citizens, accounts, transactions, etc.", $tags="", $link="../../banking-system/context/")
  WithoutPropertyHeader()
  AddProperty("Development Team","Dev/Internet Services")
  AddProperty("Owner","Customer Services")
  System(GovernmentDepartment, "Government Department", $descr="Allows citizens to view information about their accounts, and make payments.", $tags="", $link="../container/")
}

Person_Ext(Citizen, "Citizen", $descr="A member of the public", $tags="", $link="")
System_Ext(GovNotify, "GovNotify", $descr="The Government Service for sending e-maills.", $tags="", $link="")

Rel_D(Citizen, GovernmentDepartment, "Views account balances, and makes payments using", $techn="", $tags="", $link="")
Rel_D(GovernmentDepartment, BankingSystem, "Gets account information from, and makes payments using", $techn="", $tags="", $link="")
Rel_D(GovernmentDepartment, GovNotify, "Sends e-mail using", $techn="", $tags="", $link="")
Rel_D(GovNotify, Citizen, "Sends e-mails to", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml