@startuml
set separator none
title System Landscape

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

skinparam svgDimensionStyle false
skinparam preserveAspectRatio meet
Enterprise_Boundary(enterprise, "Government Body") {
  WithoutPropertyHeader()
  AddProperty("Location","Customer Services")
  Person(CitizenServiceStaff, "Citizen Service Staff", "Citizen service staff within the Government.", $tags="")
  WithoutPropertyHeader()
  AddProperty("Location","Internal Services")
  Person(BackOfficeStaff, "Back Office Staff", "Administration and support staff within the bank.", $tags="")
  System(BankingSystem, "Banking System", "Stores all of the core banking information about citizens, accounts, transactions, etc.", $tags="")[[../banking-system/context/]]
  WithoutPropertyHeader()
  AddProperty("Development Team","Dev/Internet Services")
  AddProperty("Owner","Customer Services")
  System(GovernmentDepartment, "Government Department", "Allows citizens to view information about their accounts, and make payments.", $tags="")[[../government-department/context/]]
}

Person_Ext(Citizen, "Citizen", "A member of the public", $tags="")
System_Ext(GovNotify, "GovNotify", "The Government Service for sending e-maills.", $tags="")

Rel_D(Citizen, GovernmentDepartment, "Views account balances, and makes payments using", $tags="")
Rel_D(GovernmentDepartment, BankingSystem, "Gets account information from, and makes payments using", $tags="")
Rel_D(GovernmentDepartment, GovNotify, "Sends e-mail using", $tags="")
Rel_D(GovNotify, Citizen, "Sends e-mails to", $tags="")
Rel_D(Citizen, CitizenServiceStaff, "Asks questions to", "Telephone", $tags="")
Rel_D(CitizenServiceStaff, BankingSystem, "Uses", $tags="")
Rel_D(BackOfficeStaff, BankingSystem, "Uses", $tags="")

SHOW_LEGEND(true)
@enduml